return {
  "rockyzhang24/arctic.nvim",
  dependencies = { "rktjmp/lush.nvim" },
  name = "arctic",
  branch = "main",
  priority = 1000,
}

-- return { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = false, priority = 1000 }
--
-- return { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = false, priority = 1000 }
--
-- return {
--   -- add dracula
--   { "Mofiqul/dracula.nvim" },
--
--   -- Configure LazyVim to load dracula
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "dracula",
--     },
--   },
-- }
--
-- return {
--   "catppuccin/nvim",
--   name = "catppuccin",
--   lazy = true,
--   priority = 1000,
-- }
--
-- return {
--   "rose-pine/neovim",
--   name = "rose-pine",
--   lazy = true,
--   priority = 1000,
--   opts = {
--
--     variant = "auto", -- auto, main, moon, or dawn
--     dark_variant = "main", -- main, moon, or dawn
--     dim_inactive_windows = false,
--     extend_background_behind_borders = true,
--
--     styles = {
--       bold = true,
--       italic = true,
--       transparency = false,
--     },
--
--     groups = {
--       border = "muted",
--       link = "iris",
--       panel = "surface",
--
--       error = "love",
--       hint = "iris",
--       info = "foam",
--       warn = "gold",
--
--       git_add = "foam",
--       git_change = "rose",
--       git_delete = "love",
--       git_dirty = "rose",
--       git_ignore = "muted",
--       git_merge = "iris",
--       git_rename = "pine",
--       git_stage = "iris",
--       git_text = "rose",
--       git_untracked = "subtle",
--
--       headings = {
--         h1 = "iris",
--         h2 = "foam",
--         h3 = "rose",
--         h4 = "gold",
--         h5 = "pine",
--         h6 = "foam",
--       },
--       -- Alternatively, set all headings at once.
--       -- headings = "subtle",
--     },
--   },
-- }
